from pathlib import Path
import shutil

import matplotlib.pyplot as plt
import numpy as np
from pptx import Presentation
from pptx.enum.text import PP_ALIGN

from build_parts2_3 import (
    clear, title, footer, rect, text, formula, image,
    GREEN, GREEN_DARK, GREEN_LIGHT, BLUE, BLUE_LIGHT, ORANGE,
    ORANGE_LIGHT, CHARCOAL, MID, LIGHT, WHITE,
)


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Presentation" / "Latent_Variable_Models_Neural_Data_Dynamics_working_07.pptx"
OUTPUT = ROOT / "Presentation" / "Latent_Variable_Models_Neural_Data_Dynamics_working_08.pptx"
ASSETS = ROOT / "Presentation" / "neuroscience_examples"
ASSETS.mkdir(parents=True, exist_ok=True)

COLORS = ["#3F78B5", "#008A45", "#EE772F"]


def make_spike_sorting():
    rng=np.random.default_rng(101)
    t=np.linspace(-1,1,52)
    templates=np.stack([
        -1.25*np.exp(-((t+.05)/.18)**2)+.42*np.exp(-((t-.30)/.25)**2),
        -.88*np.exp(-((t-.02)/.25)**2)+.58*np.exp(-((t-.38)/.20)**2),
        -1.05*np.exp(-((t+.18)/.15)**2)+.28*np.exp(-((t-.18)/.30)**2),
    ])
    n=165; waves=[]; labels=[]
    for k,tmp in enumerate(templates):
        for _ in range(n):
            waves.append(tmp+rng.normal(0,.10,len(t))); labels.append(k)
    waves=np.asarray(waves); labels=np.asarray(labels)
    X=waves-waves.mean(0); _,_,vh=np.linalg.svd(X,full_matrices=False); pcs=X@vh[:2].T
    centers=np.stack([pcs[labels==k].mean(0) for k in range(3)])
    d=((pcs[:,None,:]-centers[None,:,:])**2).sum(-1)
    resp=np.exp(-d/(2*np.median(d.min(1)))); resp/=resp.sum(1,keepdims=True)
    rgb=np.array([[.25,.47,.71],[0,.54,.27],[.93,.47,.18]])
    soft=resp@rgb
    fig,axes=plt.subplots(1,2,figsize=(9.2,4.4),gridspec_kw={"width_ratios":[1,1.25]})
    for k,(tmp,col) in enumerate(zip(templates,COLORS)):
        idx=np.where(labels==k)[0][:30]
        axes[0].plot(t,waves[idx].T,color=col,alpha=.08,lw=.7)
        axes[0].plot(t,tmp,color=col,lw=2.5,label=f"neuron {k+1}")
    axes[0].set_title("Detected waveform snippets",loc="left",weight="bold")
    axes[0].set_xlabel("time around spike"); axes[0].set_ylabel("voltage")
    axes[0].legend(frameon=False); axes[0].spines[["top","right"]].set_visible(False); axes[0].grid(alpha=.12)
    axes[1].scatter(pcs[:,0],pcs[:,1],c=soft,s=14,alpha=.72,edgecolors="none")
    axes[1].scatter(centers[:,0],centers[:,1],c=COLORS,s=150,marker="X",edgecolors="white",lw=1.5)
    axes[1].set_title("Soft source assignment in feature space",loc="left",weight="bold")
    axes[1].set_xlabel("waveform PC 1"); axes[1].set_ylabel("waveform PC 2")
    axes[1].spines[["top","right"]].set_visible(False); axes[1].grid(alpha=.12)
    fig.patch.set_facecolor("white"); [ax.set_facecolor("white") for ax in axes]
    fig.tight_layout(); fig.savefig(ASSETS/"spike_sorting_gmm.png",dpi=210,facecolor="white"); plt.close(fig)


def make_poisson_hmm():
    rng=np.random.default_rng(102); T=260; N=18
    states=[]; k=0
    while len(states)<T:
        dur=int(rng.integers(24,55)); states.extend([k]*dur); k=(k+1)%3
    states=np.asarray(states[:T])
    base=np.array([1.2,3.5,7.5])[:,None]
    tuning=rng.lognormal(mean=0,sigma=.45,size=(3,N)); rates=base*tuning
    counts=rng.poisson(rates[states]*.12)
    post=np.full((T,3),.025)
    for t,s in enumerate(states):
        post[t,s]=.95
    # Blur transitions to communicate posterior uncertainty rather than perfect labels.
    kernel=np.exp(-.5*(np.arange(-6,7)/2.2)**2); kernel/=kernel.sum()
    for j in range(3): post[:,j]=np.convolve(post[:,j],kernel,mode="same")
    post/=post.sum(1,keepdims=True)
    fig,axes=plt.subplots(2,1,figsize=(9.4,5.0),sharex=True,gridspec_kw={"height_ratios":[2.2,1]})
    for n in range(N):
        ts=np.repeat(np.where(counts[:,n]>0)[0],counts[counts[:,n]>0,n])
        axes[0].scatter(ts,np.full_like(ts,n),s=5,c="#333537",marker="|",linewidths=.7)
    axes[0].set_ylabel("neuron"); axes[0].set_title("Population spikes generated by persistent discrete regimes",loc="left",weight="bold")
    axes[0].spines[["top","right"]].set_visible(False)
    im=axes[1].imshow(post.T,aspect="auto",origin="lower",cmap="viridis",vmin=0,vmax=1,interpolation="nearest")
    axes[1].set_yticks([0,1,2],labels=["rest","prepare","move"]); axes[1].set_ylabel("state"); axes[1].set_xlabel("time bin")
    fig.colorbar(im,ax=axes[1],fraction=.02,pad=.015,label="posterior probability")
    fig.patch.set_facecolor("white"); [ax.set_facecolor("white") for ax in axes]
    fig.tight_layout(); fig.savefig(ASSETS/"poisson_hmm_neural.png",dpi=210,facecolor="white"); plt.close(fig)


def make_plds():
    rng=np.random.default_rng(103); T=180; N=24
    A=np.array([[.985,-.105],[.105,.965]])
    z=np.zeros((T,2)); z[0]=[2.2,.15]
    for t in range(1,T): z[t]=A@z[t-1]+rng.normal(0,.035,2)
    C=rng.normal(0,.34,(N,2)); d=np.full(N,-1.05)
    lam=np.exp(z@C.T+d); counts=rng.poisson(lam)
    fig,axes=plt.subplots(1,2,figsize=(9.4,4.6),gridspec_kw={"width_ratios":[1.05,1]})
    for n in range(N):
        ts=np.repeat(np.where(counts[:,n]>0)[0],counts[counts[:,n]>0,n])
        axes[0].scatter(ts,np.full_like(ts,n),s=5,c="#333537",marker="|",linewidths=.65)
    axes[0].set_title("Observed population spikes",loc="left",weight="bold"); axes[0].set_xlabel("time"); axes[0].set_ylabel("neuron")
    axes[0].spines[["top","right"]].set_visible(False)
    grid=np.linspace(-2.5,2.5,18); xx,yy=np.meshgrid(grid,grid); pts=np.c_[xx.ravel(),yy.ravel()]
    vel=pts@A.T-pts
    axes[1].quiver(pts[:,0],pts[:,1],vel[:,0],vel[:,1],color="#B8DCCB",alpha=.8,angles="xy",scale_units="xy",scale=1)
    axes[1].plot(z[:,0],z[:,1],c="#008A45",lw=2.4)
    axes[1].scatter(z[0,0],z[0,1],c="#EE772F",s=65,label="initial state",zorder=3)
    axes[1].scatter(0,0,c="#333537",s=75,marker="X",label="fixed point",zorder=3)
    axes[1].set_title("Inferred continuous latent trajectory",loc="left",weight="bold")
    axes[1].set_xlabel("latent 1"); axes[1].set_ylabel("latent 2"); axes[1].legend(frameon=False)
    axes[1].set_aspect("equal"); axes[1].spines[["top","right"]].set_visible(False); axes[1].grid(alpha=.12)
    fig.patch.set_facecolor("white"); [ax.set_facecolor("white") for ax in axes]
    fig.tight_layout(); fig.savefig(ASSETS/"plds_neural.png",dpi=210,facecolor="white"); plt.close(fig)


def build():
    make_spike_sorting(); make_poisson_hmm(); make_plds()
    shutil.copy2(SOURCE,OUTPUT); prs=Presentation(OUTPUT)

    # 15 — spike sorting as a finite-mixture source-assignment problem.
    s=prs.slides[14]; clear(s); title(s,"Finite mixture: which neuron generated each waveform?",15,"NEURAL EXAMPLE")
    formula(s,"zₙ ∼ Categorical(π)",.55,1.18,3.65,.66,20,BLUE_LIGHT,BLUE)
    formula(s,"xₙ | zₙ=k ∼ N(μₖ,Σₖ)",.55,2.05,3.65,.66,19,GREEN_LIGHT,GREEN)
    text(s,"xₙ: waveform features\nzₙ: source-neuron identity",.72,2.98,3.25,.72,17,CHARCOAL,True,PP_ALIGN.CENTER)
    formula(s,"p(zₙ=k | xₙ)",.82,4.08,3.10,.66,22,ORANGE_LIGHT,ORANGE)
    text(s,"soft assignment preserves uncertainty\nfor overlapping waveforms",.72,4.92,3.28,.65,16,GREEN_DARK,True,PP_ALIGN.CENTER)
    image(s,ASSETS/"spike_sorting_gmm.png",4.45,1.12,8.35,4.95)
    rect(s,1.08,6.15,11.18,.55,GREEN_LIGHT,GREEN,True,.8)
    text(s,"The latent variable answers a source question; time is not yet part of the model.",1.35,6.25,10.65,.32,17,GREEN_DARK,True,PP_ALIGN.CENTER)
    footer(s,15,"Conceptual finite-mixture view; modern spike sorting uses richer waveform, drift, and refractory constraints")

    # 16 — Poisson HMM for discrete neural regimes.
    s=prs.slides[15]; clear(s); title(s,"Poisson HMM: infer discrete neural regimes",16,"NEURAL EXAMPLE")
    formula(s,"zₜ | zₜ₋₁ ∼ Categorical(P[zₜ₋₁,:])",.55,1.22,5.20,.72,18,ORANGE_LIGHT,ORANGE)
    formula(s,"yₜ,ₙ | zₜ=k ∼ Poisson(λₖ,ₙ)",.55,2.17,5.20,.72,20,BLUE_LIGHT,BLUE)
    text(s,"zₜ: rest / prepare / move\nyₜ,ₙ: spike count of neuron n",.85,3.18,4.60,.78,18,CHARCOAL,True,PP_ALIGN.CENTER)
    formula(s,"p(zₜ=k | y₁:T)",1.20,4.30,3.90,.68,22,GREEN_LIGHT,GREEN)
    text(s,"posterior state probability",1.42,5.10,3.45,.35,15,MID,True,PP_ALIGN.CENTER)
    image(s,ASSETS/"poisson_hmm_neural.png",5.92,1.15,6.82,4.95)
    rect(s,1.05,6.13,11.25,.57,GREEN_LIGHT,GREEN,True,.8)
    text(s,"Temporal persistence denoises state assignments, but the latent trajectory remains discrete.",1.30,6.24,10.75,.32,17,GREEN_DARK,True,PP_ALIGN.CENTER)
    footer(s,16,"Synthetic illustration: population spike counts with state-dependent Poisson rates")

    # 17 — PLDS for continuous dynamics and spike-count observations.
    s=prs.slides[16]; clear(s); title(s,"PLDS: continuous neural dynamics from spikes",17,"NEURAL EXAMPLE")
    formula(s,"zₜ = A zₜ₋₁ + εₜ",.55,1.20,4.02,.66,21,GREEN_LIGHT,GREEN)
    formula(s,"λₜ = exp(C zₜ + d)",.55,2.08,4.02,.66,21,LIGHT,None)
    formula(s,"yₜ,ₙ ∼ Poisson(λₜ,ₙ)",.55,2.96,4.02,.66,21,BLUE_LIGHT,BLUE)
    text(s,"continuous latent state\n→ firing rates\n→ discrete spike counts",.92,4.10,3.30,1.05,19,CHARCOAL,True,PP_ALIGN.CENTER)
    image(s,ASSETS/"plds_neural.png",4.72,1.12,8.07,5.00)
    rect(s,1.00,6.14,11.32,.56,ORANGE_LIGHT,ORANGE,True,.8)
    text(s,"PLDS replaces a discrete state label with a low-dimensional trajectory governed by linear dynamics.",1.25,6.25,10.82,.32,17,ORANGE,True,PP_ALIGN.CENTER)
    footer(s,17,"PLDS = Poisson linear dynamical system; a standard LDS instead uses Gaussian observations")

    prs.save(OUTPUT); print(OUTPUT)


if __name__=="__main__":
    build()
